apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::261180309990:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-19YQDAVVBH5HC
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::261180309990:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-12-04T18:05:38Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapRoles: {}
        f:mapUsers: {}
    manager: eksctl.exe
    operation: Update
    time: "2020-12-04T18:05:38Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1646"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: d0eeabbc-b7a1-4690-bd41-c4fccad149fb
